name: rumour
description: "Anonymous room-code chat app built with Flutter & Firebase."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0

  # Networking
  http: ^1.2.0

  # Local storage for identity + cache
  shared_preferences: ^2.2.2

  # UUID generator
  uuid: ^4.5.0

  # Date formatting
  intl: ^0.19.0

  # Provider state management
  provider: ^6.1.2

  # Cached images (avatars)
  cached_network_image: ^3.3.1

  # Animation package
  flutter_animate: ^4.2.0

  # Pin code input
  pin_code_fields: ^8.0.1

  # Google Fonts
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/app_logo.png

flutter_native_splash:
  color: "#0D0D0D"
  image: assets/icons/app_logo.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center
