// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeLcTgXLvrzQhG5TBdkS5fwG5TA7nstL4',
    appId: '1:913832430742:web:128f6630cb2c0b49c146b7',
    messagingSenderId: '913832430742',
    projectId: 'rumour-5843d',
    authDomain: 'rumour-5843d.firebaseapp.com',
    storageBucket: 'rumour-5843d.firebasestorage.app',
    measurementId: 'G-EXKW4QWWM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6KqsINQYC0PU25DJ5UUcxV5BWpK93j64',
    appId: '1:913832430742:android:2ca0cb3413db711fc146b7',
    messagingSenderId: '913832430742',
    projectId: 'rumour-5843d',
    storageBucket: 'rumour-5843d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiJ5B_tEXDgrml6cXcqz1zxZWP3iQuy0A',
    appId: '1:913832430742:ios:2c25bcfb5142be42c146b7',
    messagingSenderId: '913832430742',
    projectId: 'rumour-5843d',
    storageBucket: 'rumour-5843d.firebasestorage.app',
    iosBundleId: 'com.example.rumour',
  );
}
